XIVY-9217 removed unneccessary replacements in Sphinx conf.py
axonivy/build-container pull request #62
Opened 2022-10-14 12:47 UTC by phochstr

I added the bash based universal placeholder substitution. 
Therefore, we can remove the almost complete placeholder substitution from Spinx.

This PR removes the replacements, along with the no longer needed function to calculate the major release number from the complete release number.

2022-10-14 12:49 UTC, phochstr commented
FYI: I checked - there is currently no Axon Ivy Platform placeholder (|ivy-platform| in the documentation.

2022-10-14 13:04 UTC, alexsuter requested changes
You can not remove this, until you fix all branches (release/10.0, release/8.0) because they all use the same container.

1) introduce new container version -> pls not.
2) fix all branches on core repo -> better solution. needs more work.

doc-factory and ortal is also using this contianer, we need to check if they need this stuff.

2022-10-17 07:03 UTC, phochstr commented
Portal does not use any of our substitutions.

I am unaware of the DocFactory documentation at this time.

2022-10-24 08:50 UTC, alexsuter commented
@phochstr can we merge now?

2022-10-24 08:59 UTC, alexsuter approved these changes
Ok, you can merge and moving story to done. thanks

2022-10-24 09:00 UTC, merged